const topPanel = document.getElementById('topPanel');
const textData = ['Is this site generated by AI?', 'On this blank canvas, I want to write/tell my story.', 'Where is the dark theme?', 'There is something I wanna tell you']; // Text array
const placedTextBoxes = [];

function getRandomPosition(width, height) {
  const panelRect = topPanel.getBoundingClientRect();

  // Calculate random X and Y positions, keeping within bounds
  const randomX = Math.floor(Math.random() * (panelRect.width - width));
  const randomY = Math.floor(Math.random() * (panelRect.height - height));

  return { x: randomX, y: randomY };
}

function isValidPosition(newRect) {
  for (let placedText of placedTextBoxes) {
    const placedRect = placedText.getBoundingClientRect();

    // Check if the new element collides with existing ones
    if (
      newRect.left < placedRect.right &&
      newRect.right > placedRect.left &&
      newRect.top < placedRect.bottom &&
      newRect.bottom > placedRect.top
    ) {
      return false;
    }
  }
  return true;
}

function placeRandomText(content) {
  const textElement = document.createElement('div');
  textElement.className = 'random-text';
  textElement.innerHTML = content;

  topPanel.appendChild(textElement);

  const textRect = textElement.getBoundingClientRect();

  let position, isValid;

  // do {
  position = getRandomPosition(textRect.width, textRect.height);
  textElement.style.left = position.x + 'px';
  textElement.style.top = position.y + 'px';

  // const newRect = textElement.getBoundingClientRect();
  // isValid = isValidPosition(textRect);

  // } while (!isValid);

  // Store placed element to avoid future overlaps
  placedTextBoxes.push(textElement);
}

// Add each text box randomly in the topPanel
textData.forEach(
  (text) => setTimeout(() => placeRandomText(text), 5000)
) 
